apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypgsql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypgsql
  template:
    metadata:
      labels:
        app: mypgsql
    spec:
      containers:
        - name: mypgsql
          image: ghcr.io/velito86/postgresql:v1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: hastedb
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password 
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: hastedb
#            - mountPath: /docker-entrypoint-initdb.d
#              name: hastedb-init-scripts
      volumes:
        - name: hastedb
          persistentVolumeClaim:
            claimName: haste-pv-claim
#        - name: hastedb-init-scripts
#          persistentVolumeClaim:
#           claimName: haste-postgres-pv-claim
            
