apiVersion: apps/v1
kind: Deployment
metadata:
  name: haste-server
  labels:
    app: haste-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haste-server
  template:
    metadata:
      labels:
        app: haste-server
    spec:
      containers:
      - name: haste-server
        image: ghcr.io/velito86/haste-server/haste-server:v3
        ports:
        - containerPort: 7777
        envFrom:
          - configMapRef:
            name: haste-server-config
        env:
        - name: STORAGE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: STORAGE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password